<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-RV54SM4" ignored="4" name="Test(failed)" tests="2" failures="2" timestamp="10 Apr 2020 18:43:14 GMT" time="0.007" errors="0">
  <testcase name="sampleCheck3" time="0.002" classname="com.TestNG.SamplePackage.SampleTest1">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at com.TestNG.SamplePackage.SampleTest1.sampleCheck3(SampleTest1.java:22)
at com.TestNG.SamplePackage.TestNGFailedCaseRerun.failedCasesRerun(TestNGFailedCaseRerun.java:21)
... Removed 53 stack frames]]>
    </failure>
  </testcase> <!-- sampleCheck3 -->
  <testcase name="sampleCheck6" time="0.0" classname="com.TestNG.SamplePackage.SampleTest2">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at com.TestNG.SamplePackage.SampleTest2.sampleCheck6(SampleTest2.java:22)
at com.TestNG.SamplePackage.TestNGFailedCaseRerun.failedCasesRerun(TestNGFailedCaseRerun.java:21)
... Removed 53 stack frames]]>
    </failure>
  </testcase> <!-- sampleCheck6 -->
  <testcase name="sampleCheck2" time="0.0" classname="com.TestNG.SamplePackage.SampleTest1">
    <ignored/>
  </testcase> <!-- sampleCheck2 -->
  <testcase name="sampleCheck5" time="0.0" classname="com.TestNG.SamplePackage.SampleTest2">
    <ignored/>
  </testcase> <!-- sampleCheck5 -->
  <testcase name="sampleCheck4" time="0.0" classname="com.TestNG.SamplePackage.SampleTest2">
    <ignored/>
  </testcase> <!-- sampleCheck4 -->
  <testcase name="sampleCheck1" time="0.0" classname="com.TestNG.SamplePackage.SampleTest1">
    <ignored/>
  </testcase> <!-- sampleCheck1 -->
</testsuite> <!-- Test(failed) -->
