<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-RV54SM4" name="com.TestNG.SamplePackage.TestOne" tests="3" failures="1" timestamp="23 Apr 2020 03:40:29 GMT" time="0.032" errors="0">
  <testcase name="testCaseThree" time="0.012" classname="com.TestNG.SamplePackage.TestOne"/>
  <testcase name="testCaseOne" time="0.015" classname="com.TestNG.SamplePackage.TestOne"/>
  <testcase name="testCasetwo" time="0.005" classname="com.TestNG.SamplePackage.TestOne">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	testCaseOne Second hard assert failed expected [true] but found [false],
	testCaseone Third soft assert failed expected [true] but found [false],
	testCaseThree Second hard assert failed expected [true] but found [false],
	testCaseThree Third soft assert failed expected [true] but found [false],
	testCasetwo Second soft assert failed expected [true] but found [false],
	testCasetwo Third soft assert failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
testCaseOne Second hard assert failed expected [true] but found [false],
testCaseone Third soft assert failed expected [true] but found [false],
testCaseThree Second hard assert failed expected [true] but found [false],
testCaseThree Third soft assert failed expected [true] but found [false],
testCasetwo Second soft assert failed expected [true] but found [false],
testCasetwo Third soft assert failed expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.TestNG.SamplePackage.TestOne.testCasetwo(TestOne.java:29)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testCasetwo -->
</testsuite> <!-- com.TestNG.SamplePackage.TestOne -->
